### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by mlabrum** [nuke-build/nuke#1047]
### Description

Hello,

My team and I are impressed with what you've done with this project. It's a fantastic build system that you've developed.

I'm wondering about the state of this project as I'm evaluating this for use within our company and clients, and where I see quick replies to issues ( and further asking for pull requests), I can't see much action on the pull request side.

The last closed PR was 31st Aug, and there are a number of really handy tool pull requests that are dated back to the start of this year. 

Are you currently accepting pull requests for this project? (As we would like to contribute back to the community) or looking for maintainers? or would you prefer tools be packaged as external nuget packages? 

Kind regards,
Matt

**Comment by valadas** [comment]
I'll let @matkoch reply to the details of the question but if you want to get an idea of how active this project is, look at the releases page instead. I don't want to speak out of order but I believe many bugfixes/enhancements come here through commits rather than PRs. I can assure you this product if great, very stable and under active development. You won't go wrong with Nuke!

**Comment by matkoch** [comment]
Hi @mlabrum 

it sounds like you're interested in some kind of prioritization. For that I suggest you reach out via info@nuke.build and we can discuss further.

Just know that I'm unavailable until end of next week.

Best regards

**Comment by matkoch** [comment]
@mlabrum just FYI, I haven't received anything.
