### ISSUE TITLE
Change telemetry to opt-in

### ISSUE THREAD

**Issue by RobSmyth** [nuke-build/nuke#1051]
### Description

Change telemetry feature to opt-in. The current opt-out implementation makes the tool less desirable (and maybe not permitted) in some organizations. There are issues here despite it being as being intended to be benign and anonymous like:

1. The opt-out is machine specific (environment variable). So it is difficult to ensure opt-out across multiple developer and build boxes and time (team churn). It would be a LOT better to be able to opt-out in the csproj file. At least that allows for code security auditing and if off by default it will make security vetting much easier on tool update.

2. While anonymous, given the EU data protection and online privacy regulations, opt-out will not be received well. The data being sent is considerable. Being real-time there is still a small possibility of identifying source organization.

EU regulation quote:

> `When a company or organisation asks for your consent, you have to make a clear action agreeing to this, for example by signing a consent form or selecting yes from a clear yes/no option on a webpage.
> 
> It is not enough to simply opt out, for example by checking a box saying you don't want to receive marketing emails. You have to opt in and agree to your personal data being stored and/or re-used for this purpose.`

I get it. Data is collected in good intent and is intended to be anonymous. But given the data security policies in organizations this will be a killer in some cases. Such security issues will only get more attention as time passes.

**Comment by totollygeek** [comment]
> The current opt-out implementation makes the tool less desirable.

You shouldn't even be using .NET if that's the case. The `dotnet` CLI itself also uses an "opt-out" approach on that matter.

At this point we don't really see this as a real issue.

**Comment by matkoch** [comment]
The GDPR is meant to protect the privacy of EU citizens – just FYI because I saw you're living in Australia. Anyway, if you take a look at the documentation, you can see that none of the data points contain personal data, so it's quite incomparable to the scenario you cited about collecting real names and email addresses for the purpose of marketing. Furthermore, I would assume that if a company cares about security, there should be processes to propagate such settings to developer machines and CI/CD agents automatically. If that's not the case, I frankly see no reason to make it the problem of this project.

For the record: NUKE is way more transparent than the GDPR actually requires. Just as with the .NET CLI telemetry, there are no obligations to ask for permission for the data that is being collected.
