### ISSUE TITLE
Banner, target names etc. seem to have the wrong color when using a dark console theme

### ISSUE THREAD

**Issue by batzen** [nuke-build/nuke#1161]
### Usage Information

7.0.0

### Description

Banner, target names etc. seem to have the wrong color when using a dark console theme.

In my case they are have the same color as the background and are thus invisible:
![image](https://user-images.githubusercontent.com/1971030/236697788-441d5541-7a66-43a8-9749-9d59c2d759ed.png)

When switching to a light theme they get visible:
![image](https://user-images.githubusercontent.com/1971030/236697811-a3017601-9d50-4752-875e-4f3544925952.png)

### Reproduction Steps

In my case, just run a build.

### Expected Behavior

Colors should be visible.

### Actual Behavior

See description.

### Regression?

This worked perfectly fine in 6.3.

Screenshot from a different project using v 6.3.
![image](https://user-images.githubusercontent.com/1971030/236697868-13a36649-1f40-4220-94a8-6de8a2dcc716.png)

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
There were no changes about logging, AFAIR. Still working for me as well
<img width="511" alt="JetBrains Rider-ConsoleApp1 – Program cs-2023-05-07-yksmXroZ@2x" src="https://user-images.githubusercontent.com/5005566/236701500-9983130d-394f-4c4f-ad18-baae2be3d789.png">
<img width="560" alt="JetBrains Rider-ConsoleApp1 – Program cs-2023-05-07-hRKevH6W@2x" src="https://user-images.githubusercontent.com/5005566/236701501-406a1564-6b5b-4ed9-9702-0f9b6992fa2d.png">

**Comment by lahma** [comment]
I'm also seeing this behavior on Windows 11. Here are some observations.

`SupportsAnsiOutput` is false because of:

https://github.com/nuke-build/nuke/blob/09d4dc03f3e10b5c130271f99fe5458bd788861b/source/Nuke.Build/Logging.cs#L28

But based on Serilog source it states for `AnsiConsoleTheme`: "A console theme using the ANSI terminal escape sequences. Recommended for Linux and Windows 10+."

This is why `SystemConsoleHostTheme` is chosen and it has this for `Debug`:

https://github.com/nuke-build/nuke/blob/09d4dc03f3e10b5c130271f99fe5458bd788861b/source/Nuke.Build/Theming/SystemConsoleHostTheme.cs#L29

If this value is changed to say `[ConsoleThemeStyle.LevelDebug] = new() { Foreground = ConsoleColor.Gray },` the output starts to show up. This theme also has empty for `ConsoleThemeStyle.Text` but that value isn't being used anywhere I guess.

So probably problem is two-fold, should/could use `AnsiConsoleHostTheme` on Windows 10+ (tested by returning true from `SupportsAnsiOutput` and output was fine) and terminal should have default value for Debug Foreground if being used.

**Comment by lahma** [comment]
I've created https://github.com/nuke-build/nuke/pull/1162 as proposed fix. Tested first that when `SystemConsoleHostTheme` is chosen output is correct. Second tested that adding the OS detection choses ANSI and output is again correct. Tested on Windows 11 having dark theme as OS default.

**Comment by lahma** [comment]
Workaround for now, add following to your `build.ps1`:

```
$env:TERM = "xterm"
```

**Comment by matkoch** [comment]
Someone tell me what has changed please :) I see no relevant changes.

https://github.com/nuke-build/nuke/blob/6.3.0/source/Nuke.Common/Execution/Logging.cs
https://github.com/nuke-build/nuke/blob/7.0.0/source/Nuke.Build/Logging.cs

**Comment by lahma** [comment]
Maybe it's this https://github.com/nuke-build/nuke/commit/60ca0a2914ff1e52a619360d922b6fdfd2c23651 , not defaulting to some earlier foreground anymore and causing to be empty or something?

**Comment by matkoch** [comment]
You mean [this](https://github.com/nuke-build/nuke/commit/60ca0a2914ff1e52a619360d922b6fdfd2c23651#diff-e952cb3dbe5d13b41f0b84f80f680ca3e5d290ae03dc9b926d07c4416d41efa9R110-R111), right?

```
    public static IDisposable SetAndRestore<T>(Expression<Func<T>> memberProvider, T value)
    {
        var member = memberProvider.GetMemberInfo();
        var target = memberProvider.GetTarget();
        var previousValue = member.GetValue<T>(target);
        member.SetValue(target, value);
        return new DelegateDisposable(() => member.SetValue(target, previousValue));
    }
```

Actually that should restore the previous foreground and background color.

**Comment by lahma** [comment]
Yes, earlier theme's null would have been replaced with `Console.ForegroundColor` and set then:

https://github.com/nuke-build/nuke/commit/60ca0a2914ff1e52a619360d922b6fdfd2c23651#diff-e952cb3dbe5d13b41f0b84f80f680ca3e5d290ae03dc9b926d07c4416d41efa9L111-L118

**Comment by matkoch** [comment]
Ah I see

**Comment by ricaun** [comment]
I have the same problem, in my case is showing in black.
![image](https://user-images.githubusercontent.com/12437519/236845789-2ad5000a-27ff-4524-b130-5b4f155a1786.png)
![image](https://user-images.githubusercontent.com/12437519/236845696-abd06075-f467-487b-848c-9dffa4ad8b44.png)

**Comment by ITaluone** [comment]
3rd option: (with default Powershell theme in darkmode)

![image](https://github.com/nuke-build/nuke/assets/44049228/a3bc8f0e-dc72-40b3-ad95-3d6f40d49362)
