### ISSUE TITLE
Solution.GetProject returns null

### ISSUE THREAD

**Issue by fen89** [nuke-build/nuke#1300]
### Usage Information

NUKE 7.0.6 / .NET Core SDK version 8.0.100

### Description

`Solution.GetProject()` returns null for any given existing project name.

### Reproduction Steps

- Create solution, with 1 Project, named 'Demo'

```cs
partial class Build : NukeBuild
{
  Target Compile.Executes(() =>
  {
      var allProjects = Solution.GetAllProjects("*");
  
      foreach (var project in allProjects)
      {
          Log.Information("- {project}", project.Name);
      }

      Log.Information("project found: '{value}'", Solution.GetProject("Demo"));
  });
}
```

This produces the following log output:

```
16:09:30 [INF] - Demo
16:09:30 [INF] project found: 'null'
```

### Expected Behavior

The correct project name should be returned instead of null. 

### Actual Behavior

`Solution.GetProject()` returns null

### Regression?

Works in v7.0.0 with the following:

```cs
partial class Build : NukeBuild
{
  Target Compile.Executes(() =>
  {
      var allProjects = Solution.AllProjects;
  
      foreach (var project in allProjects)
      {
          Log.Information("- {project}", project.Name);
      }

      Log.Information("project found: '{value}'", Solution.GetProject("Demo"));
  });
}
```

This produces the following log output:

```
16:09:30 [INF] - Demo
16:09:30 [INF] project found: '[path omitted]/Demo.csproj'
```

### Known Workarounds

Downgrade to v7.0.0

### Could you help with a pull-request?

No

**Comment by matkoch** [comment]
![2023-11-29-JetBrains Rider-nuke-issue – Build cs-001374](https://github.com/nuke-build/nuke/assets/5005566/25128887-14e7-45be-b6bc-2fec1c7932a1)

**Comment by yonkahlon** [comment]
Hi @matkoch,

I'm also experiencing this issue.

If I do: `Solution.GetAllProjects(<projectName>)` I get the correct project, but if I do `Solution.GetProject(<projectName>)` I get null.

Also using v7.0.6 and .net8

**Comment by matkoch** [comment]
I just showed you above that it's working for me. If you want any meaningful resolution you should provide a repro. +1 doesn't add any information.

**Comment by yonkahlon** [comment]
Is your example with .net 6?

As soon as I get a repo together, I'll let you know :-)

**Comment by peterbomers** [comment]
This can be reproduced when the sources of a project are located in an additional sub-directory.

**Comment by mschulze46** [comment]
> This can be reproduced when the sources of a project are located in an additional sub-directory.

I can confirm this. Same problem here.

**Comment by maciejgwizdala** [comment]
Hello @matkoch,

I agree with others that there is regression in .net 8.
I had to do following workaround with `using System.Linq` to just get first element from `IEnumeration<Project>` created by `DemoSolution.GetAllProjects()`, as `DemoSolution.GetProject()` returns _null_ when project is located in subfolder:

```csharp
[Solution("dotnet/Demo/Demo.sln")] readonly Solution DemoSolution;

partial class Build : NukeBuild
{
  Target CodeTests.Executes(() =>
  {
        Project[] testProjects = new Project[]
        {
            DemoSolution.GetProject("Tests1"), // project dir: dotnet/Demo/Tests1
            DemoSolution.GetAllProjects("Tests2").First() // project dir: dotnet/Demo/OtherTests/Tests2
        };
  
        foreach (var project in testProjects)
        {
            Log.Information("- {project}", project.Name);
        }
  });
}
```

**Comment by matkoch** [comment]
1. Go to [CHANGELOG.md](https://github.com/nuke-build/nuke/blob/develop/CHANGELOG.md#701--2023-05-15)
2. Search for `Solution.GetProject`
3. ...
4. Profit

Folks, seriously, I don't write these notes for myself.

**Comment by maciejgwizdala** [comment]
> 1. Go to [CHANGELOG.md](https://github.com/nuke-build/nuke/blob/develop/CHANGELOG.md#701--2023-05-15)
> 2. Search for `Solution.GetProject`
> 3. ...
> 4. Profit
> 
> Folks, seriously, I don't write these notes for myself.

@matkoch Thanks a lot for your response and guidance that this is not bug, but intentional change.

Please note that CHANGELOG itself is not [Solution & Project documentation page](https://nuke.build/docs/common/solution-project-model/), where information about `Solution.GetAllProjects()` method and difference to `Solution.GetProject()` should be added in the first place and where new nuke.build adopters expect it to be. As documentation seems to be a little bit outdated to current features, people keep asking how to use something, as it's not obvious right away.

So please, do not take this offensive and thanks a lot for all your effort in nuke.build development. Keep up good work! :)

**Comment by matkoch** [comment]
@maciejgwizdala please don't take offense either, but this sounds like an excuse to me. There are multiple ways for you to find and investigate what you're looking for, but you treated open-source like a black box. I'm not critizising that this issue was created, but honestly I'd like to see less expectations towards me as maintainer, and more effort on the consumer side. No one seemed to have looked at the Git history, tried to pinpoint the exact version, or debugged into the code. Also, neither your or the OP code sample is even compilable.
