### ISSUE TITLE
Guidance on creating new Tasks or Plugins

### ISSUE THREAD

**Issue by GeorgDangl** [nuke-build/nuke#15]
For deploying websites to Azure and IIS, I'm using usually Microsoft WebDeploy. There's no *.exe available via NuGet, but a dll package: [Microsoft.Web.Deployment](https://www.nuget.org/packages/Microsoft.Web.Deployment/)

Now I've drafted a small Task so I can use it with Nuke, the code is available as Gist:
https://gist.github.com/GeorgDangl/5521ef94bc6cae85793f8842f64fa3c5
(Consider this an early WIP)

I'd like to ask for some guidance how such a plugin should be published, especially these questions would be interesting:

  * Should `WebDeploySettings ` inherit from `ToolSettings`? When calling functions via a dll, there's no need for a `ToolPath` property. I've marked it obsolete in the draft, which gives me compiler warnings, otherwise, I've got a unused property. Should I just inherit from `ISettingsEntity` or just use a its own class?
  * The required NuGet package is only available for the full .Net framework, so the build is Windows only. No problem for my use cases, but would this be OK?
  * Are there any naming conventions for external plugins that are planned to be released on NuGet? For example, can I release it as `Nuke.Tools.WebDeploy`?

**Comment by matkoch** [comment]
@GeorgDangl skype or gitter maybe? it's ithrowexceptions or nuke-build/nuke

**Comment by matkoch** [comment]
### General
- Use `ControlFlow` instead of exceptions

### Tasks
- Use `Configure<MySettings> settings` instead of passing in `MySettings`

### Metadata
- Must be language agnostic
- If possible, copy the original documentation and use vim macros to transform into json
- Use formattings tags like `<b>`, `<em>`, `<c>`, `<ul>` and so on
- Avoid quotes if possible
- Add references for change detection
