### ISSUE TITLE
Microsoft Teams Integration

### ISSUE THREAD

**Issue by RLittlesII** [nuke-build/nuke#252]
Add the ability to send messages from Nuke to MicrosoftTeams

**Comment by bytemarcz** [comment]
Anymore details on this? It looks like we might be able to use the Microsoft Graph API to support messages being sent from Nuke to MicrosoftTeams. By the way, trying to see what I can submit a pull request on for Hacktoberfest!!

Cheers! 
Mario

**Comment by matkoch** [comment]
Always welcome. I can't do anything as I don't have any Microsoft Teams workspaces.

**Comment by VolkmarR** [comment]
Hi @matkoch, I use Teams at work. If the goal of this issue is to post a message to a teams channel, I could use the [Incomming Webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors#incoming-webhooks) connector to solve that. The advantage of this kind of connector is very easy to configure in Teams, but they are limited to post messages to channels. If that's ok, you can assign this issue to me.

**Comment by GeorgDangl** [comment]
Hey @VolkmarR, if you’re taking that, here’s an example of how this is done: https://github.com/shibayan/keyvault-acmebot/blob/master/KeyVault.Acmebot/Internal/WebhookClient.cs#L66

Looks pretty simple😀

<blockquote><img src="https://avatars2.githubusercontent.com/u/1356444?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/shibayan/keyvault-acmebot">shibayan/keyvault-acmebot</a></strong></div><div>Automated ACME issuer for Azure Key Vault (App Gateway / Front Door / CDN / others) - shibayan/keyvault-acmebot</div></blockquote>

**Comment by VolkmarR** [comment]
@GeorgDangl yes, the task should not be that difficult. IMO the hardest part is to create a class that simplifies the creating of the message json.

**Comment by matkoch** [comment]
@VolkmarR you can take a look at the Slack tasks I think.
