### ISSUE TITLE
Preserve color output of CLTs

### ISSUE THREAD

**Issue by matkoch** [nuke-build/nuke#256]
Having colors mixed of multiple CLTs can be considered an advantage, for instance for dotnet CLI, but also a disadvantage, since there are is no consistency.

Any solution would need to:
- be able to capture CLT output and evaluate it (for error/warning summary)
- show colored output via `Console.WriteLine` with CMD, ConEmu, Cmder, PowerShell, Bash, etc.

**Comment by matkoch** [comment]
@LordMike @mvestergaard

**Comment by mvestergaard** [comment]
I'm not sure I understood your comment regarding the CustomLogger in DotNetTasks, because it doesn't seem to work for that either, here is a test execution first run through dotnet.exe directly, and then through nuke

![image](https://user-images.githubusercontent.com/2027834/54315484-851f7b80-45de-11e9-9e4b-b3bd7fde027a.png)

**Comment by matkoch** [comment]
Well, I haven't seen your specific use case and you just mentioned MSBuild.

If you look at the implementation of `DotNetTasks.CustomLogger`, you'll see that it filters for `... warning:` and `... error:`. I'm not aware of how standardized the output for test runners is, but you could wrap the custom logger, and add implementation to detect `[SKIP]` at the end probably.

**Comment by matkoch** [comment]
People want parallel target execution but also colored output. So there's a bit of a trade-off :)

If you have more questions on that, I'd recommend you to visit the Slack workspace.
