### ISSUE TITLE
Behavior during/after setup execution

### ISSUE THREAD

**Issue by jussimattila** [nuke-build/nuke#257]
First of all, my initial impression of Nuke is great, this looks like something I can see myself using for a number of upcoming projects!

I have two small questions after bootstrapping Nuke into a single project.

1) First of all, running the build succeeds but I get this warning every time: `Assertion failed: Could not complete checking build configurations within 500 milliseconds.` There is a closed issue related to this error message but I didn't understand if this is something I should do something about or if it will be resolved in a later build of Nuke.

2) The bootstrapper asked about test folder, but it doesn't appear to have used that information for anything. My source code are projects in `src` and tests are projects in the same folder and that is what I provided as answers to the bootstrapper. Was it supposed to add testing step in the build?

I did not edit any of the files generated by the process, just ran the bootstrapped build. Nevertheless, the generated files are clean, easy to follow and I am ready to start customizing the build!

**Comment by matkoch** [comment]
_For questions/feature requests you're generally required to have the project starred_ 😃 

1. The `CheckBuildProjectConfigurationsAttribute` is responsible for that. When the build project is added to the solution, it should not have a build configuration. Otherwise, it would attempt to build itself and probably fail (because it's also executing). This attribute scans all solution files below the `.nuke` file with a timeout of 500 milliseconds. You can either increase the value on the attribute, or check what is taking so long and how many solution files are there.
2. The question solely indicates that the `TestDirectory` property is being generated. Neither test target will be added, nor folders will be created. This however, could be an improvement for later.

**Comment by jussimattila** [comment]
Starred now, of course! 😄

My solution folder is quite large and also contains several projects with front-end components depending on `node-sass`. For some reason, npm package for node-sass contains an `.sln` file. These things probably explain why the scanning takes a bit longer.

Thanks a lot for your quick response!

**Comment by matkoch** [comment]
@jussimattila could you create a new issue and describe the project structure? we can either fix this by not traversing certain directories, or by limiting the directory depth.

**Comment by DanielToft** [comment]
I'm having the same issue with "Assertion failed: Could not complete checking build configurations within 500 milliseconds". It only happens when I have a node_modules folder, inside one of my projects.
