### ISSUE TITLE
SonarScannerBegin is missing a method to set the /o parameter

### ISSUE THREAD

**Issue by Rick-van-Dam** [nuke-build/nuke#304]
Currently there is no way to set the `/o` parameter for SonarScannerBegin as no method exists for it. Please add this as its needed for sonarcloud.

**Comment by matkoch** [comment]
Please note the [contribution guidelines](https://github.com/nuke-build/nuke/blob/master/CONTRIBUTING.md).

**Comment by Rick-van-Dam** [comment]
@matkoch Sad to see this was closed and marked as wontfix so quickly with such a blunt response, especially when its clear this is simply missing from the implementation and this issue was created in a effort to rectify this small issue. 

You say you only accept pull requests for this but as iam unable to find the code for this iam also unable to create a pull request. In the end I just worked around this issue. 

For anyone running into this issue I worked around it like so:
```
    [PackageExecutable("dotnet-sonarscanner", @"tools\netcoreapp2.1\any\SonarScanner.MSBuild.dll")]
    private static Tool SonarScanner;
```
Then in the code of your target you can simply do this and pass the arguments manually:
```
SonarScanner($"begin /k:{projectKey} /o:{organisation} /v:{version} /d:sonar.login={SonarCloudLogin} /d:sonar.host.url={server} /d:sonar.exclusions={exclusions} /d:sonar.branch.name={branch}");
```

**Comment by matkoch** [comment]
@Barsonax I'm sorry, but I don't see this as an issue that's worth having to be filed. First, there is the possibility to use `SetArgumentConfigurator` as stated [here](http://www.nuke.build/docs/authoring-builds/cli-tools.html#custom-arguments). Second, if we keep issues for every missing argument individually for a tool, that would become extremely cumbersome to manage. We're already making a compromise for [requested tools](https://github.com/nuke-build/nuke/issues/259), but as you see, none of that has been picked up since then.

If you're unable to find the bits that need to get changed, that's another thing. First, I recommend reading the [related documentation](http://www.nuke.build/docs/writing-addons/code-generation.html). And if there are open questions then, I think it's best to post on Slack.
