### ISSUE TITLE
Access to IProcess on ProcessException

### ISSUE THREAD

**Issue by ron-myers** [nuke-build/nuke#310]
Within our build process, there are several command-line tools we call.  Some of of these tools fail in known ways that should not stop the build from continuing. For example, `dotnet nuget push` with duplicate packages and other internal tools have specific ExitCodes they return based on the response type. Depending on the exitcode of the used tool, the overall build should or should not continue. 

When these tools are called via Nuke, `ProcessException`(which inherits from `Exception` and has an internal `IProcess` property) is thrown. This leave us with, as I see it, the options: 

1. `completeOnFailure: true` - which may catch false negatives.
1. try catch and parse the error messages (ugly but our current approach)
1. fail the build on these non-failure cases

There may be another available approach that we have missed. I am happy to investigate another approach and/or submit a pull request for this change.

**Comment by hdougie** [comment]
We also have this in our build process. In particular, the issue has been thrown up when checking in files via tf.exe. The process can throw a non-critical error when there are no actual changes in the checked-in files. 

Currently, our build process fails on such errors, when actually, we would like it to continue whilst outputting a warning rather than an error. Currently, the only way I can see of doing this is to parse the output manually, whereas it would be nice to be able catch the error and handle the exit code manually.

**Comment by matkoch** [comment]
#326
