### ISSUE TITLE
Assertion on PathExecutable should optional

### ISSUE THREAD

**Issue by mortengjesing** [nuke-build/nuke#345]
### Description
Would like a way to manually check PathExecutable in code. At the moment this code
```
[PathExecutable("chmod")]
readonly Tool Chmod;
```
TThrows this error `Assertion failed: Could not find 'chmod' via 'C:\Windows\System32\where.exe'.` it should be possible to do a null check in build code.

Something like this
```
[PathExecutable("chmod", AllowNull = true)]
readonly Tool Chmod;

if (Chmod != null)
{
    Chmod("");
}
```

**Comment by totollygeek** [comment]
This by the way, I also had to struggle with. Since I use the same Nuke build on a couple of build agents. Only on one of them I use `docker-compose` as a tool. Because of that, it fails on the others, since the tools is not needed. But even if it is not accessed, it tries to load it on startup. So the question is. Do we need it to be `AllowNull` or do we just need to initialize it in a lazy manner.

**Comment by cmenzi** [comment]
There is also an issue when using for example having

```
[PathExecutable("powershell.exe")]
Tool PowerShellWin;
[PathExecutable("pwsh.exe")]
Tool PowerShellCore;
```
This results in a error on linux. Maybe we can add a condition or I like the idea of @totollygeek doing a lazy evaluation.
