### ISSUE TITLE
OutputSink is not very extendable 

### ISSUE THREAD

**Issue by Rurouni** [nuke-build/nuke#387]
### Description
When upgrading to new version of Nuke I've realized that IOutputSink changed to abstract class OutputSink. Before we had adapter that was implementing IOutputSink and overriding WriteError to write to stderr channel but otherwise delegating it straight into original instance of IOutputSink created by the framework. IOutputSink as interface was allowing extending original behaviour without any modifications. With abstract class design and WriteError being protected, some other abstract members internal and all implementations marked as internal means that it's just not possible to neither inherit from base OutputSink nor any implementations

### Alternatives
It would be great to have IOutputSink interface back

**Comment by erkinkas** [comment]
existing `AzurePipelinesOutputSink` works well enough with `Azure DevOps Services`

<img width="1399" alt="LoggerTest_Build" src="https://user-images.githubusercontent.com/13992901/76627345-bfde2b80-6532-11ea-8cdc-2a628a6ce6e3.png">

but it's not that pretty with `Azure DevOps Server 2019`

<img width="1328" alt="LoggerTest_Release" src="https://user-images.githubusercontent.com/13992901/76627486-05025d80-6533-11ea-89bf-5c2cddfa0b4c.png">

I understand, that `Azure DevOps Server 2019` is an older version of Azure Devops and most likely it will not be supported by Nuke.

However, it would be super useful to make OutputSink extendable, so people like me (who stuck with older versions 😃) could implement they own solution.

**Comment by sbakharev** [comment]
Hi guys. Thanks you all for Nuke!

My situation is identical to one described by @Rurouni. I used my own IOutputSink implementation to avoid the problems described by @erkinkas and also at #264 when using a little bit outdated Azure DevOps server. This is important for us because DevOps is the primary place where we inspect build/test errors and garbled output significantly complicates reading plain text.

Having an ability to implement and then override an OutputSink field seemed like an elegant extension point. Now there is no way to change the behavior hardcoded at the NukeBuild class. It would be nice to at least have an option to select an OutputSink out of a predefined list with some non-colored alternative available.

**Comment by sbakharev** [comment]
P.S. Tested Nuke 0.24 with my current version of DevOps (Dev17.M153.5, released about half a year ago). DevOps definitely has made some improvements for colored output, but it's still not perfect.

![screenshot-2020 03 31-03_59_10](https://user-images.githubusercontent.com/31010533/77976184-e65adf80-7304-11ea-98a9-959a0f35f4db.png)

And even though this is most probably not Nuke's fault, an ability to disable colored output would be highly appreciated. After all colored logs is not a top priority feature IMO.

P.P.S. What are those grouping logging commands? Official documentation does not tell anything about them.

**Comment by matkoch** [comment]
Hi everyone, I don't plan to address this any time soon. If it's important for you, please consider a sponsorship.
