### ISSUE TITLE
ProcessException only captures stderrout when exit code is non zero

### ISSUE THREAD

**Issue by macsux** [nuke-build/nuke#407]
### Description
When tool runs and exists with non zero exception, PrcoessException is raised. However, it only captures STDERROUT (if it's present), ignoring rest of STDOUT. IProcess is also internal making it impossible to extract any relevant STDOUT messages. This mainly shows up in `dotnet` tool were actual error details will be printed to STDOUT instead of STDERROUT.

https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tooling/ProcessException.cs#L28-L37

### Alternatives

1. Expose additional property on ProcessException to access STDOUT
2. Make IProcess non internal

**Comment by matkoch** [comment]
I decided against automatically showing STD output, but you can run the build with `verbose` logging level.

**Comment by mnasir083** [comment]
**Issue**: We're experiencing issue with flaky tests that are challenging to fix because they rely on FakeltEasx or CastleProject, either directly or indirectly. 

To address this, we opted to implement a retry mechanism using Polly for DotNetTest. 
We encountered a problem where we captured a ProcessException when these flaky tests failed, but the actual test failure exception was not accessible.

**Solution**: We encountered similar that IProcess is internal. To resolve this issue, we used Reflection to access the IProcess and capture the output log. This allowed us to determine the exception if a genuine flaky test failure had occurred, and if so, we initiated test retries. 

Verbose is an option but we decided not go with Verbose as it will result in cluttering huge logs.
