### ISSUE TITLE
Nuke isn't packing referenced tools with global tool

### ISSUE THREAD

**Issue by krankenbro** [nuke-build/nuke#437]
### Description
http://www.nuke.build/docs/sharing-builds/global-tools.html

> One great advantage that NUKE implements, is that all tool references will be automatically packed with the global tool. That means that package references having a ./tools folder, like GitVersion or xunit.runner.console, are automatically part of the global tool package. This makes the build self-contained.

Actually after dotnet pack we have only the tool packed without the referenced packages

### Steps to reproduce

1. add to  csproj:
![image](https://user-images.githubusercontent.com/42555001/76557229-db4e2580-64a3-11ea-823e-d96a30f1cb62.png)

2 dotnet pack

### Relevant log output
![image](https://user-images.githubusercontent.com/42555001/76557308-00db2f00-64a4-11ea-9fc7-b33d6d5c99dd.png)

**Comment by cmenzi** [comment]
Yes, I've encountered the same issue. This is the behavior of NuGet. See https://github.com/NuGet/Home/issues/9132#event-3004692576

I've achieved it by repacking the NuGet package after pack.

What I did I created a `.props` where the package references are defined with a `Pack=true` attribute. You can also use your `.csproj`, but I use the `.props` file, because I use share build with NuGet package instead of GlobalTool.

So, I can inject some properties into `_build.csproj` via package updates.

Here is how I did it:
1. Get the package after dotnet pack
1. Extract the nupkg(zip)
1. Add all dependencies to with the `Pack` attribute to nuspec file with `exclude=All` (development dependency), I think don't need that, because you also need those dependencies during runtime.
1. Do another dotnet pack, but now with the modified `NuspecFile` file

```xml
var nugetPackage = Glob.Files(ArtifactsDirectory, "*.nupkg").NotEmpty().Single();
var propsFile = Glob.Files(BuildAssemblyDirectory, "*.props").NotNull().Single();
var propsContent = XDocument.Load(BuildAssemblyDirectory / propsFile);
var packageReferencesToAddToNuspec = propsContent.Descendants("PackageReference").Where(x => x.Attribute("Pack").Value == "True");

var extractedPackageDir = TemporaryDirectory / nugetPackage;
UncompressZip(ArtifactsDirectory / nugetPackage, extractedPackageDir);

var nuspecFile = Glob.Files(extractedPackageDir, "*.nuspec").NotEmpty().Single();
var nuspecDocument = XDocument.Load(extractedPackageDir / nuspecFile);
var namespaceName = nuspecDocument.Root.GetDefaultNamespace().NamespaceName;

var dependenciesElementName = XName.Get("dependencies", namespaceName);
var groupElementName = XName.Get("group", namespaceName);

var groupElement = nuspecDocument.Descendants(dependenciesElementName).Single().Element(groupElementName);

foreach (var packageReference in packageReferencesToAddToNuspec)
{
    var dependencyElement = new XElement(XName.Get("dependency", namespaceName));
    dependencyElement.Add(new XAttribute("id", packageReference.Attribute("Include").Value), new XAttribute("version", packageReference.Attribute("Version").Value), new XAttribute("exclude", "All"));
    groupElement.Add(dependencyElement);
}

nuspecDocument.Save(extractedPackageDir / nuspecFile);

DotNetPack(_ => _
    .SetProject(MainProject)
    .SetProperty("NuspecFile", extractedPackageDir / nuspecFile)
    .SetOutputDirectory(ArtifactsDirectory)
    .SetProperty("NoWarn", "$(NoWarn)%3BNU5048"));
```
