### ISSUE TITLE
Add ListReleases to OctopusTasks

### ISSUE THREAD

**Issue by lars-nielsen** [nuke-build/nuke#446]
### Description
List Releases allows us to calculate what the next release name should be, and give the possibility to check if the version already exists

### Alternatives
Call OctopusTasks.Octopus($"list-releases --outputFormat=json --server={server} --apiKey={apiKey} --project=\"{project}\""); and deserialize the result

If accepted ill supply the pull request

**Comment by matt-richardson** [comment]
Coincidentally, I’m most of the way through putting together a change to the octopus cli to expose all the information needed to auto generate the specification. 
Got something mostly working on the octopus cli side, just hacking around on the nuke side to generate the file.

**Comment by lars-nielsen** [comment]
That sounds awesome.

what is the timeframe, i think i can create a pr tomorrow.

But if youre done soon then i wont bother

lør. 21. mar. 2020 23.21 skrev Matt Richardson <notifications@github.com>:

**Comment by matt-richardson** [comment]
I suspect I wont have time to complete it in the next few days (juggling too many things). Let's say "a week".

But I've just re-read your PR and

> deserialize the result

jumped out at me... I hadn't thought about handling that. I'll keep that in mind.

In terms of backwards compat though, a PR here would lock in the type names etc so that is something to keep in consideration.
