### ISSUE TITLE
Remember Task Runner Explorer configuration after Visual Studio restart

### ISSUE THREAD

**Issue by paolofulgoni** [nuke-build/nuke#453]
### Description

The [Visual Studio extension for Nuke](https://marketplace.visualstudio.com/items?itemName=nuke.visualstudio) adds the Task Runner Explorer integration, which is very useful.

Unfortunately the configuration applied in this VS window (i.e. the bindings with VS events) are lost after VS restart. It would be much better if the settings are restored after reopening the solution.

I don't know if that's an issue of VS or the Nuke extension.

**Comment by matkoch** [comment]
Just FYI, I don't plan to work on that even in the far future. If you want to work on that yourself, the repo is at https://github.com/nuke-build/visualstudio.

<blockquote><img src="https://avatars1.githubusercontent.com/u/26774874?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuke-build/visualstudio">nuke-build/visualstudio</a></strong></div><div>VisualStudio extension. Contribute to nuke-build/visualstudio development by creating an account on GitHub.</div></blockquote>

**Comment by paolofulgoni** [comment]
You want me to use Rider, right? 😂 just kidding

**Comment by matkoch** [comment]
Certainly not a bad idea :>

**Comment by dmealo** [comment]
I just would like to add a vote for supporting the large community of Enterprise developers using Visual Studio.  Also, would PRs to that repo be merged, or is that a dead end?

Our team was considering switching to this tool from Cake, but this topic makes things look like this tool might be heading in the same direction of not supporting common developer workflows in the long run.

**Comment by matkoch** [comment]
Think I’m gonna need a few days to let that sink.

**Comment by paolofulgoni** [comment]
@matkoch I'm sorry but I don't understand what you mean

**Comment by matkoch** [comment]
@DavidMtbg how about you sponsor the project to make your company issues our priority? It's beyond my comprehension that THIS WORKFLOW is worth making shady assumptions about what direction we're taking.

**Comment by totollygeek** [comment]
> 
> 
> I just would like to add a vote for supporting the large community of Enterprise developers using Visual Studio. Also, would PRs to that repo be merged, or is that a dead end?
> 
> Our team was considering switching to this tool from Cake, but this topic makes things look like this tool might be heading in the same direction of not supporting common developer workflows in the long run.

I, myself, am an "enterprise developer" (since I have enterprise license for Visual Studio) and as such, I consider helping out open-source projects as Nuke, by submitting pull requests and help out the community, whose resources I am using on a daily basis. 
An "enterprise developer" is not a title to brag about **IF** you consider that you should be given support for non-profit, open-source, **FREE** software just because you said so. You either pay for it and demand support, or you go and fix it yourself by adding value of helping others.
The code is here. Open. Available for fixes whenever you need them. Just submit a fix and you will have it. 
If you think this is not your job, then you are not an "enterprise developer". You are just a jerk 🤷‍♂️

**Comment by paolofulgoni** [comment]
@DavidMtbg do you confirm that you can reproduce the issue on your side?
If so, is you or your team willing to fix it?

**Comment by dmealo** [comment]
I am sorry if my message came across the wrong way - it was certainly not my intention.  I only wanted to get to the root of why the feature had value to it's users - because Visual Studio is possibly used by many.  But I am just learning about this tool, so perhaps that is not the case.  I definitely wasn't trying to brag about being an enterprise developer.  I actually work for a consulting firm.  I meant that this tool seemed to be aimed at enterprise developers since it is a tool for what is largely an enterprise platform - .NET.

I also was excited about all of the work that has been done on the project, admire it, and would like to be able to use it for our process so that its community and support grow and perhaps sponsorship out of that growth.  It seems there may be others interested in that scenario as well.  If I were already using it, perhaps I would have just sought to do the work myself or commission it, but I am just in the discovery and evaluation phase with this tool, so I'm looking at whether it will even work for our needs.

Again, apologies for any unintended tone, assumptions or assertions that came through my message and best wishes for your project!

**Comment by ghost** [comment]
@DavidMtbg sponsoring this project sounds as a good future collaboration bridge. Especially when as a consultant this tool means profit.
Stay in touch mate 👊

**Comment by matkoch** [comment]
@DavidMtbg I still struggle to see the pain this particular issue is causing. Just enable the checkboxes. How many times do you have to restart VS?

**Comment by matkoch** [comment]
So who would look at that?
