### ISSUE TITLE
Azure Pipelines - AzurePipelinesBuildReason does not support 'ResourceTrigger'

### ISSUE THREAD

**Issue by winromulus** [nuke-build/nuke#712]
### Description
Getting the BuildReason while running in Azure Pipelines results in Exception. It seems that not all Trigger values are supported (as seen from https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#triggers)

### Steps to reproduce

1. Run build in Azure Devops where the build is triggered by a pipeline resource.
2. Access `AzurePipelines.Instance.BuildReason`

### Relevant log output
```
Value 'ResourceTrigger' could not be converted to 'AzurePipelinesBuildReason'.

```

**Comment by matkoch** [comment]
PR plz

**Comment by winromulus** [comment]
@matkoch - Please read the following as not being posted in any aggressive, passive-aggressive or entitled way.

Why was this closed? I was aiming to put out a PR for it but if this is closed how does that help with visibility on the project? What if others face the same issue and perhaps they're aiming to point a PR to this issue?
With all due respect, I do understand that this is an Open Source project but at the same time it feels like either contributions are micro-managed or issues are hidden just to lower the issue count.
To summarize my humble opinion:
- You ask for a star before being able to report an issue or getting any visibility on the project (a bit underhanded but sure)
- You close issues with subcomponents (CLI tools etc.) as being invalid issues (how are people supposed to track them? are two people hitting the same issue supposed to work on the same problem?) but at the same time advertise them as valid functionalities of the deliverables
- You close reported issues with requesting a PR. Requesting a PR is valid, but closing an issue which is still an issue is not. While a PR might be pending, people are hitting the same issue and there's no visibility.

I will be contributing with the PR for this because that is the correct way of being part of a community, but at the same time I'm starting to regret pushing for this utility to my projects and employers due to lack of visibility into potential issues.

**Comment by matkoch** [comment]
> A bit underhanded but sure

Haha, okay. Please take a seat if you read on.

> You close issues with subcomponents (CLI tools etc.) as being invalid issues

Yes, as per contribution guidelines. I wrote them for a reason, and you obviously didn't care to read them.

> You close reported issues with requesting a PR.

Yes, this is exactly the opposite of micro-management. This PR would have been a single-line change, but you deem it worthy to start a full-blown discussion here. _Your_ issue is very neglectable for the success of the project, same as with CLI tool support. They don't affect any core component and therefore I close them with the request of a PR. If I had an issue for each and every CLI tool or missing enum value, I'd spent most of my time triaging. And otherwise, these issues would just be sitting there without anyone caring except waiting for _someone_ to _maybe_ address them because I personally won't.

> I'm starting to regret pushing for this utility to my projects and employers

Thanks for the intro, but after the _underhanded_, this is the second time you come across _quite_ entitled. I'm caring about the developers that are understanding and take part in the longevity of the project. Hence, I recently changed the contribution guidelines so that any issue / pull-request requires a sponsorship. Please keep this in mind if you're still interested in creating the PR. I was going for _allowing_ this one to go in without, but your response there doesn't leave me with a good feeling.

Take care.

**Comment by winromulus** [comment]
@matkoch 
Your project, your rules. I just wanted to help report and fix an issue. I have now a better understanding.  Good luck with the new philosophy.

**Comment by matkoch** [comment]
Thanks for your good intentions, but honestly, nothing you did was of any help, particularly that you couldn't read the contribution guidelines and accuse me of being underhanded. Anyways, take care and good luck finding another project.

**Comment by narcis-sy** [comment]
@matkoch you are bringing shame to the oss community. If you’re interested in only sponsorships, convert it into a paid project and stop wasting everybodies time when they try to contribute. Unbelievable!

**Comment by matkoch** [comment]
❤️

**Comment by matkoch** [comment]
Glad that I've found the OSS community spokesman.

**Comment by jnovick** [comment]
I just ran into this issue too. Can you re-open this? I'll put up the PR to fix it once the issue is re-opened. The documentation with the proper values is here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services
