### ISSUE TITLE
DockerTasks SetMemory setting not correct value

### ISSUE THREAD

**Issue by VladyslavLishchyna** [nuke-build/nuke#777]
### Usage Information

Nuke.Common 5.0.2, Windows/Linux

### Relevant Code / Invocations

```code
DockerTasks.DockerBuild(s => s.SetMemory(12000));
```

### Expected Behavior

Docker change memory parameter and does not have exceptions

### What actually happened?

In DockerUpdateSettings (and other classes) SetMemory() building like
`.Add<long>("--memory {value}", this.Memory) `

In docker documentation https://docs.docker.com/config/containers/resource_constraints/ saids that parameter memory must be with symbol "m"

![image](https://user-images.githubusercontent.com/24877107/129016053-548d4704-563e-4c3e-b2f0-381db012d576.png)
so i think needed to be
`.Add<long>("--memory {value}m", this.Memory) `

In Windows code with Set Memory() works (actually I think that docker can't catch this parameter ), but in linux have exception
![image (15)](https://user-images.githubusercontent.com/24877107/129016485-1958d592-e0ef-416d-b777-63ca84aadb93.png)

**Comment by eatdrinksleepcode** [comment]
As noted in the documentation page you linked, just above the screenshot you took, "m" for megabytes is not the only option:

> Most of these options take a positive integer, followed by a suffix of b, k, m, g, to indicate bytes, kilobytes, megabytes, or gigabytes.

What that page doesn't make clear, and is actually a little difficult to find a definitive answer for in the Docker documentation, is what happens when you don't specify a suffix. That information is in the [man page for "docker build"](http://manpages.org/docker-build) for the `memory-swap` option:

> The format of LIMIT is `<number>[<unit>]`. Unit can be b (bytes), k (kilobytes), m (megabytes), or g (gigabytes). If you don't specify a unit, b is used. Set LIMIT to -1 to enable unlimited swap.

Assuming this also applies to `--memory`, that means not specifying a suffix, which Nuke doesn't, means the value should be interpreted as a number of bytes; which makes sense, I think.

Now, it might be handy to be able to specify a suffix; but that would require the parameter to be typed as `string`, which would allow a much larger range of invalid values. And there are convenient ways to specify large numbers in C# other than using a suffix. So I don't think this warrants changing the tool.

**Comment by matkoch** [comment]
Agree with what @eatdrinksleepcode wrote. I imagine though that we could add some helper extension methods ala `5.MegaByte()` and change the type of the `Memory` argument to `Byte` (not the CLR type) with a few implicit conversions. That would make the interface more driving. If anyone is open to investigate this, feel free to open a PR. Otherwise I'll just keep it in the back of my head.

**Comment by eatdrinksleepcode** [comment]
Agreed, I can imagine a lot of potentially useful value types for representing commonly used CLI parameters. Would also work well with custom type formatters (#126).
