### ISSUE TITLE
ProcessStartInfo must not clear environment variables

### ISSUE THREAD

**Issue by cmenzi** [nuke-build/nuke#797]
Currently, when providing some environment variables, the process cannot start anymore, because some important OS environment variables are not there.

A good example is the Azure Cli, when providing for example `AZURE_CORE_ONLY_SHOW_ERROR` 

```csharp
..., environmentVariables: new Dictionary<string, string> { { "AZURE_CORE_ONLY_SHOW_ERROR", "true" } })
```

It results in

```
ProcessException: Process 'az.cmd' exited with code 1.
   > "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" apim api list --resource-group my-rg --service-name my-apim
   @ C:\data\xxx\xxx\xxx
Error output:
   Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python
   Python runtime state: preinitialized
```

When setting this env-var upfront via `EnvironmentInfo.SetVariable()`. The process starts as expected.

The issues comes from the fact, that when you create a `ProcessStartInfo` then by accessing `Environment` property adds the system and user specific environment variables to the dictionary and returning them. See: https://github.com/dotnet/runtime/blob/cd90de06833dec07bda80994e2e990f5f2be9f47/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.cs#L78

https://github.com/nuke-build/nuke/blob/068ce4bdd135cf928150e8d68751453b91767b8c/source/Nuke.Common/Tooling/ProcessTasks.cs#L185

**Comment by matkoch** [comment]
Hi Cedric, I think you and I had a discussion related to this, but I will gladly repeat it. Anything that doesn't fall under "high-impact / showstopper" requires a sponsorship here. This is also mentioned in the issue template. Apparently, you chose the blank template – I don't know why, because this here reads like a bug report.

**Comment by cmenzi** [comment]
Sure. Just created a comment from code line. Then no template is shown.  It's just that mostly all CLT's could be impacted in this issue. 

I'm not sure if ever tested passing `environmentVariables` to any of your 50 integrated CLI's. 

I thought it's highly impacted. EnvironmentVariables are core of processes, build systems, ...

if you `Clear()` them, how should thing work? None of the CI/CD system provided variables will be used anymore. 

You welcome.

**Comment by cmenzi** [comment]
Basically, your Core API is broken:

```
public delegate IReadOnlyCollection<Output> Tool(string arguments = null, string workingDirectory = null, IReadOnlyDictionary<string, string> environmentVariables = null, int? timeout = null, bool? logOutput = null, bool? logInvocation = null, bool? logTimestamp = null, string logFile = null, Action<OutputType, string> customLogger = null, Func<string, string> outputFilter = null);
```

There is a parameter `environmentVariables`, which is unusable or breaks CI/CD processes.

**Comment by matkoch** [comment]
> Basically, your Core API is broken

It would be surprising that a "core API" that hasn't been touched in a very long time gets suddenly broken. In most cases it can be assumed that the API is not correctly used.

- When using the fluent API, you can clear the environment variables with `.ClearProcessEnvironmentVariables()`, replace them with `.SetProcessEnvironmentVariables(new Dictionary<string, string> { ["key"] = "value" })`, and add new pairs with `.AddProcessEnvironmentVariable("key", "value")`
- When using the simple API (string interpolation etc.), the parameter is called `environmentVariables` and _NOT_ `additionalEnvironmentVariables`. When the parameter is not set, it will inherit the variables from the running process, otherwise they are _FULLY_ replaced with what is passed, hence `environmentVariables`. The most important reason for this design is that otherwise you can't run a process with all environment variables cleared.

> You welcome.

You too.

**Comment by cmenzi** [comment]
Ok, you've won. Was not obvious to me. Therefore, many thanks for explanation. Have a nice week end.

**Comment by matkoch** [comment]
Did you have any chance to follow up on the sponsorship you've mentioned?
