### ISSUE TITLE
Remove sponsorship wall for contributors

### ISSUE THREAD

**Issue by gleb-osokin** [nuke-build/nuke#806]
### Description

The cause of this issue are notices about required sponsorship for creating bug reports, feature requests and (first and foremost) pull requests.

I'm questioning this restriction, since the project might benefit a lot from voluntary contributions, while having this pay wall might appear harmful. 

Suppose I want to fix an issue within the project. I have two options:
1) do a workaround in my code or
2) clone the repo, make a fix and create a PR, because, hey, I'm doing a favor to the open source community.

Oh, wait, I have to pay a monthly subscription? Then I'd better go with the first option. Perhaps, even clone the project for my own purposes and do all the needed adjustments there.

From my point of view this goes against the idea of aligned community success. When there are fewer or no contributions, nobody wins. The users will not get a useful functionality, some will even opt out of using the project, the potential sponsors will decide that it's not worth the donations...

Yes, there are maintenance efforts for the project team. They are free to ask for sponsorship, or only check PRs/create releases once every third month, or even abandon the whole thing for some new fancy project. That's entirely up to them. Sponsorship implies no obligations.

However, once sponsorship is required for creating PRs - it is no longer a sponsorship, we're now in a buy/sell relationship. And in a buy/sell relationship there must be guarantees for the money. Therefore, it is fine to claim, say, that PRs from sponsors would be reviewed with higher priority, but prohibiting all non-sponsored PRs is an overkill.

This is the first time I see such a business model in an open source project and I admit there might be reasons that I am not aware of. So I am filing this issue for a healthy discussion on the matter.

**Comment by Structed** [comment]
I think it's clearly stated in the [contributor guidelines](https://github.com/nuke-build/.github/blob/master/.github/CONTRIBUTING.md) what the background to this policy is, and what your options are.

It's not restricting you to contribute, it's just making clear what the priorities are and it asks you to be mindful of the maintainer's investment.

**Comment by gleb-osokin** [comment]
> It's not restricting you to contribute

Unfortunately, it does. The guidelines are not as strict as PR/Bug report/feature request creation notice. The latter clearly states, that:
> To create a pull-request, you **must** be an active supporter of our community, i.e., a sponsor of NUKE ...

So, by creating a PR regardless of the notice, I have a feeling I'm circumventing the rules of the repository. Perhaps my PR will be declined immediately or, at best, ignored until the end of times. I read it as if my contributions were unwelcome here. "No offence, but we won't allow you to improve our project, unless you pay us some money". Why then make it an open source project in the first place? This is really beyond me.

Yes, maintenance has costs, and it's okay to look for ways to cover those costs. Blocking voluntary contributions, however is not a decent way to do so. I honestly believe, that even the very own existing sponsors are interested in an actively developed and improved project. That's, beside other things, something they invest in. 

It's not some big boss that says: "hey, that's a nice project, lets become sponsors and then use it within our infrastructure". It's line developers that try things out in order to, maybe, incorporate NUKE in their CI pipeline. They normally already have a solution that works, but that's just not really convenient to work with, for some reason. So they check if they could use NUKE. Very nice project, very promising, just lacks this one tiny bit, that is specific to the company's setup. And that cannot be fixed, unless the company pays to the project. As if there were not enough hurdles beside of that: diving into external project source code, cloning a repo, doing a fix, making sure that all other cases, that are not specific to the one of the company, are not broken, creating the PR, fixing all the comments. Oh, and that goes after those weeks of experimenting and migration from the old build setup, just to check if it works. And, if you've ever worked for a large company, you probably know, how long it takes to apply for some expenditure and to make it happen. A month? Two months? Who cares, we can just create our own clone of the project. Just a button click. Sometimes merge from the parent, when we want an upgrade. But that is really a lose-lose outcome. We now have to maintain our own version of NUKE, the main project didn't get any fixes and also, potentially a future sponsor - if we did end up using NUKE on a large scale, we would probably be forced to consider that option for faster PR reviews, for example.

Those are the reasons why I was really surprised to see this policy around and that's why I've created this issue.

**Comment by matkoch** [comment]
@gleb-osokin does your company sponsor any OSS project?

**Comment by Structed** [comment]
First, the guideline gives you multiple options on how to contribute.

Have you reached out to the maintainer's via Slack? I strongly believe, that if you have a good suggestion or a proposal for a PR, they would like to discuss it and would give you the option to contribute. That is - in any case - the best way to be a "good OSS citizen".

In fact, there is this specific piece in above linked contribution guideline:

> High-impact bugs may be reported/fixed at any time, feature ideas may be discussed openly on Slack

Secondly, I know the pain going through a funding request in large orgs. And I assume that exactly this was part of the decision to impose a "paywall": because of this pain, most folks would not even bother going to ask, while at the same time, these large orgs would have the most resources to fund the project and are likely the ones profiting most from using it in relation to smaller orgs.


So perhaps consider making an impact and go through that pain and help a project that saves you a lot of work by making your builds awesome.


Lastly, the guideline also states:

> [be a ...] frequent blogger/mentor, or greatly involved in any other recognized OSS project.

This is then for the folks who do not have the means to otherwise sponsor the project. This is the way to "sponsor" the project by lifting it up.

**Comment by gleb-osokin** [comment]
@matkoch to be honest, I don't know. We're a huge international company, with a recent chain of merges and acquisitions. We have a number of public repositories on github, which are considered our OSS contribution. If you mean financial sponsorship, then I'm not really sure. Could not find anything in our official docs, so, perhaps, the answer is no. We do sponsor a lot of other organizations, though, that, for example, have to deal with various kinds of environment protection, diversity support and discrimination prevention, etc. I guess, it doesn't count, does it? 
But its entirely not the point.

@Structed so you're suggesting, basically, that I have to go talk my way through Slack or by other means, just to prove that I'm even worth to be a tiny-winy contributor. Or take efforts to knock money out of our financial departments. Or become an active member - right, do you know how one becomes an active member in the first place? By submitting and fixing bugs, requesting and implementing features - all by means of PRs. And now we're in a vicious circle... You're suggesting that I really go out of my way to earn the right to create a PR. 
I could do all that. But, guess what? I am not some overzealous OSS fan, I am just an ordinary developer, who is just doing his job. I occasionally create some niceties along the way, which I'm willing to contribute back to the community. But I never insist, it's take it or leave it.

And I have a strong feeling that I'm not the only one. There are many others that could have brought true marbles to the project, but they will just not bother, because of the policy. We're developers, after all, we can always find our workaround. 
And that is my point. Not only you're declining potentially valuable contributions, but won't even know that some issues or possibilities exist, because they will never be created. It makes me really sad.

Again, you probably think, that it's just me and I'm rambling about one single PR that I was not allowed to create. I'm not. I am just sharing my feelings and saying, that there might be many others that feel the same way. Feeling that the maintainers, perhaps, cutting the branch they're sitting on.

I don't mean to offend anyone, so please forgive me if that reads a bit harsh.

**Comment by Structed** [comment]
I really don't understand what is the problem with "talking your way up on Slack".

Do you realise you have just spent probably more than 30 minutes of complaining here? Likely more?

You are complaining about a thing that is really a requirement in any OSS project: talk to the maintainer's first to not waste anyone's time (including your own) by providing something that might not be wanted.

The decision is the maintainer's how they want to govern their project and if you do not like it, you may say so, but you may be ignored because yes, you might not be the only one thinking like that, but obviously, that is not who the maintainer's want on this project.

Oh, btw: you complained so much but not even considered use one of the options given to you but decided to complain more again, spending the time you could have talked to the maintainer's on Slack to provide something that's worth everyone's time.

@matkoch I suggest you close this issue, as it clearly violates the contribution guidelines and there is seemingly no interest of actually contributing.

**Comment by gleb-osokin** [comment]
>  and there is seemingly no interest of actually contributing

That's actually not true. I have created an issue/feature request first, that was closed almost immediately: https://github.com/nuke-build/nuke/issues/805

I do admit, that I, probably, did go too far in adding my personal complaints in the description there, but then, I also suggested to create another issue exactly to discuss the matter.

And that's not the whole story. I started with cloning the repo first and fixing this tiny problem. Just two lines of code, changing Console.WriteLine to Console.Error.WriteLine. But, as you rightfully noticed, the fix could break something on some build agents for some people. Or, pehaps, there were reasons that NUKE uses Console.WriteLine. Hence, I've decided to create an issue first to discuss, whether the fix is needed in the first place. The issue, that was immediately closed. 

Well, what can I say, good luck doing the whole work on your own. Oh, and unfortunately, I don't use Slack, for better or worse.

Edit: 
> and if you do not like it, you may say so

That's exactly what I did here. And yes, it's entirely up to maintainer to take or not take any further actions.

**Comment by matkoch** [comment]
@gleb-osokin this? 

https://github.com/Avira

**Comment by gleb-osokin** [comment]
@matkoch yes, and as Avira has been purchased by NortonLifeLock, there's also https://github.com/nortonlifelock. Also, since NortonLifeLock has also purchased Avast, it's their public repo too: https://github.com/avast. That last one looks pretty convincing, if you ask me. But all those M&As is the reason why I was somewhat unsure on your question.

By the way, I'm all for companies supporting OSS development and would even go as far as mediate some sponsorship request. However, in my very humble opinion, this should not be a blocker for individuals that just want to help.

All things aside, I am thankful to you for taking the time to read all of this.

**Comment by matkoch** [comment]
Don't you think it's a bit of a stretch to say your company contributes to OSS when it only has 4 repositories with not a single one having more than 10 commits? It also looks odd to take credit for what other companies have done, just because they happened to be acquired by the same parent company. As you said, this was all recent.

> By the way, I'm all for companies supporting OSS development and would even go as far as mediate some sponsorship request. However, in my very humble opinion, this should not be a blocker for individuals that just want to help.

You're clearly not and I have zero hope for that. Following your argument, there would just be one "blocker" after another which would hold off your multi-national company to take a few bucks from its million and billion yearly revenue to actually help to sustain projects that they're benefiting from. I see you contributed to NUnit. Was that also a blocker? Are you now sponsoring? I'm sure you're not. I've been around in OSS long enough to say that this behavior is the reason for the frequent burnout of maintainers.

And no, you're not alone, but luckily the number of like-minded people chiming in here drastically decreased when I introduced the sponsorship requirement. Of course, every now and then, there is still someone who knows better, ignores the rules, and wants to educate us on what's best for the project.

Besides @Structed I had two people reaching out to me, saying they're mad because of your entitlement and that they want to respond. I'll do us all a favor and end this discussion so that we don't waste any more time on it.
