### ISSUE TITLE
Introduce target odering

### ISSUE THREAD

**Issue by arodus** [nuke-build/nuke#93]
Currently the executing and dependsOn targets are not following any order (#90). 

Example: 
```c#
Target Clean => 
   .Executes(() => {});

Target Compile =>
  .DependsOn(Clean)
  .Executes(() => {});

Target Coverage => 
 .Executes(() => {});
```

When executing `nuke Compile+Coverage`, it's possible that `Coverage` is executed before `Clean` and therefore the coverage results will be deleted. To solve that problem without the usage of `DependsOn` (hard dependency) we should introduce "soft dependencies" for targets. This basically means that the target must run before another target but doesn’t requires the other target to run.
This could be achieved by adding the functions
- `ITargetDefiniton Before(params Target[] targets);`
- `ITargetDefinition After(params Target[] targets);`

to the `ITargetDefiniton` interface. 

With this we could change the above example to this:

```c#
Target Clean => 
   .Executes(() => {});

Target Compile =>
  .DependsOn(Clean)
  .Executes(() => {});

Target Coverage => 
 .After(Clean)
 .Executes(() => {});
```
Instead of defining `.After(Clean)` in the `Coverage` target it would be also possible to define `.Before(Coverage)` in the `Clean` target.

The table below shows the executed commands and the resulting execution order.

| Command  | Target Execution Order |
| ------------- | ------------- |
|`nuke coverage` | `Coverage` |
|`nuke compile` | `Clean` -> `Compile` | 
|`nuke compile+coverage` | `Clean` -> `Compile` or `Coverage` -> `Compile` or `Coverage` (the target which didn't run before) |
|`nuke clean` | `Clean` |
|`nuke clean+coverage` | `Clean` -> `Coverage` |

**Comment by dennisdoomen** [comment]
The soft dependencies do help in this example, but just consider a large project with a lot of targets. In most of my projects, I have a single `Default` target that wants to run `Clean` first and then runs 10 other targets of which most could run in parallel if this feature ever landed. However, they all must run after `Clean`. Now, each target must _know_ about the existence of the `Clean` target and have a `After(Clean`) clause added everywhere. I love Nuke, especially because the way dependencies work, but sometimes I just _do_ want to specify some ordered dependencies in such a way I don't have to couple my targets together too much.

**Comment by matkoch** [comment]
@dennisdoomen so what you're essentially asking for, is  a `BeforeAll`?

**Comment by dennisdoomen** [comment]
Something like that, yes....

**Comment by matkoch** [comment]
I think there's one cheap and one expensive way. Cheap way adds ordering to all other targets, but HTML plan would look bad. Expensive would only add orderings to initial targets (i.e., without dependencies).
