### ISSUE TITLE
Add ability to Register a Cleanup/Post Target Execution

### ISSUE THREAD

**Issue by dansiegel** [nuke-build/nuke#972]
### Description

CI Platforms like Azure DevOps or GitHub actions provide a way for steps to trigger an automatic cleanup / post task. These get defined from the task and occur at the very end of the build pipeline. For instance this occurs with the checkout & caching steps in GitHub Actions. This provides a clean API for producing components which are loosely coupled with other components, and prevent other components from having to explicitly know about the cleanup task that needs to occur whether execution of the pipeline was successful or not. This would be a very useful concept to add directly to Nuke to allow Targets to Register a Post Execution action which is not directly triggerable, but occurs automatically if the Target is invoked at the end of the build. 

![image](https://user-images.githubusercontent.com/3860573/177357568-b2fc87a5-d2a0-460b-b3c4-eca0ac98c9aa.png)

### Usage Example

```code
public interface IHazAppleCertificate : INukeBuild
{
    Target InstallAppleCertificate => _ => _
        .Executes(() => 
        {
            // Some logic to install the cert
        })
        .PostExecutes(() =>
        {
            // Some logic to remove the certificate
        });
}
```

### Alternative

Currently there is no alternative that would allow loosely coupling these targets.

```cs
Target InstallCertificate => _ => _
  .Executes(() =>{ /* Do Stuff */ });
  
Target RemoveCertificate => _ => _
    .TriggeredBy(InstallCertifcate)
    .After<ICompile>()
    .AssuredAfterFailure()
    .Executes(() => { /* Do Cleanup */ });
```

This creates tight coupling where either you need to know what target the cleanup can safely come after or know to add the cleanup target explicitly rather than allowing this to occur naturally.

**Comment by willsmith9182** [comment]
When using multiple Targets with PostExecutes what order would you expect cleanup tasks to be invoked in? Origianl build Target order or inverted (like the github example)?

**Comment by dansiegel** [comment]
I know both GitHub Actions and Azure DevOps have the same sort of behavior. Personally I think it makes a lot of sense with that sort of inverse or last-in-first-out strategy. Just looking at the actual GitHub Actions Workflow as a sample I think you could safely say you wouldn't want the Checkout Task to execute it's Post Action before the Cache Post Action.

**Comment by matkoch** [comment]
Build extensions are the better alternative at the moment. See https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Execution/BuildExtensionAttributeBase.cs

**Comment by matkoch** [comment]
I thought about this and I'm sure by now that this is not a good direction. It would increase the complexity of the model a lot with very little benefit and further imply limitations. For instance:

- You cannot skip the cleanup (for troubleshooting)
- You cannot execute the cleanup on another agent (not everything is file-system relevant)

Since the question was raised, it's also evident that it's not clear in what order the cleanup is executed. Meanwhile, target dependencies and `nuke --plan` give a very clear understanding about the order.

Btw, meanwhile, I'm also opposed to using build extensions for this. The proper way would probably be something like:

```
interface IAppleCertificate : INukeBuild
{
    Target InstallCertificate => _ => _
        .Triggers(RemoveCertificate)
        .Executes(() => {});

    Target RemoveCertificate => _ => _
        .AssuredAfterFailure()
        .Executes(() => {});
}

class Build : NukeBuild, IInstallAppleCertificate
{
    Target Compile => _ => _
        .DependsOn<IAppleCertificate>(x => x.InstallCertificate)
        .Before<IAppleCertificate>(x => x.RemoveCertificate)
        .Executes(() => {});
}
```

The part with `DependsOn` and `Before` could probably be moved into a new extension method similar like:

```
Target Compile => _ => _
    .Using<IAppleCertificate>()
    .Executes(() => {});
```

Both targets, `InstallCertificate` and `RemoveCertificate`, could be marked with `[Setup]` and `[Cleanup]` attributes respectively.
